default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: end-of-file-fixer
        exclude: '.*\.rst'

-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        args:
        - --config=.flake8

-   repo: https://github.com/omnilib/ufmt
    rev: v2.8.0
    hooks:
    - id: ufmt
      additional_dependencies:
        - black == 24.2.0
        - usort == 1.0.2
